name: docs
on: [push]

jobs:
    docs:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                julia-version: ['1.3.0']
                julia-arch: [x64]
        steps:
            - uses: actions/checkout@v1.0.0
            - name: "Set Up Julia"
              uses: julia-actions/setup-julia@latest
              with:
                  version: ${{ matrix.julia-version }}
                  arch: ${{ matrix.julia-arch }}
            - name: "Instantiate Docs"
              run: julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
            - name: "Build and Deploy Docs"
              run: julia --project=docs docs/make.jl
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
